name: 'My Custom Action'

on:
  workflow_call:
    inputs:
      additional_variable_names:
        type: string
        default: ""
    secrets:
      additional_variable_values:
        description: 'Var values.'
        required: false

env:
  additional_variable_values: ${{ secrets.additional_variable_values }}

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    steps:
    - name: 'Print Input'
      run: |
        echo ${{ inputs.additional_variable_names }}
        echo ${{ env.additional_variable_values }}
    - name: 'Set Environment Variables'
      if: ${{ inputs.additional_variable_names != '' }} && ${{ env.additional_variable_values != '' }}
      run: |
        set -f
        IFS=,
        var_name_array=(${{ inputs.additional_variable_names }})
        var_value_array=(${{ env.additional_variable_values }})
        echo "${#var_name_array[@]}"
        echo "${#var_value_array[@]}"
        for key in "${!var_name_array[@]}";
        do
          echo ${var_name_array[$key]}
          echo ${var_name_array[$key]}=${var_value_array[$key]} >> $GITHUB_ENV
        done
    - name: 'Print Variables'
      run: |
        echo ${{ env.ACTION_VAR_1 }}
        echo ${{ env.AWS_DEFAULT_REGION }}
        echo ${{ env.AWS_DEFAULT_REGION_2 }}