name: 'My Custom Action'
description: 'My Custom Action'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

env:
  ACTION_VAR_1: 'action_variable_1_value'  

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    steps:
    - name: 'Print Variables'
      run: |
        echo ${{ env.ACTION_VAR_1 }}