name: 'My Custom Action'

on:
  workflow_call:
    inputs:
      blah:
          type: string
          required: true
    
env:
  ACTION_VAR_1: 'action_variable_1_value'

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    steps:
    - name: 'Print Variables'
      run: |
        echo ${{ env.ACTION_VAR_1 }}
        echo ${{ github.event.inputs.blah }}