name: 'My Custom Action'

on:
  workflow_call:
    inputs:
      additional_variable_names:
        type: string
        default: ""
    secrets:
      additional_variable_values:
        description: 'Var values.'
        required: false

env:
  additional_variable_values: ${{ secrets.additional_variable_values }}

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    steps:
    - name: 'Set Environment Variables'
      if: ${{ inputs.additional_variable_names != '' }}
      run: |
        set -f
        IFS=,
        var_name_array=(${{ inputs.additional_variable_names }})
        for key in "${!var_name_array[@]}";
        do
          echo "${var_name_array[$key]}"
        done
    - name: 'Print Variables'
      run: |
        echo ${{ env.ACTION_VAR_1 }}
        echo ${{ env.AWS_DEFAULT_REGION }}