name: 'My Custom Action'

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
      additional_variable_names:
        type: string
        default: ""
    secrets:
      additional_variable_values:
        description: 'Var values.'
        required: false
jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: 'Set Environment Variables'
      if: ${{ inputs.additional_variable_names != '' }} && ${{ secrets.additional_variable_values != '' }}
      run: |
        set -f
        IFS=,
        var_name_array=(${{ inputs.additional_variable_names }})
        var_value_array=(${{ secrets.additional_variable_values }})
        for key in "${!var_name_array[@]}";
        do 
          echo "${var_name_array[$key]}=${var_value_array[$key]}" >> $GITHUB_ENV
        done
    - name: 'Print Variables'
      run: |
        echo ${{ env.ACTION_VAR_1 }}
        echo ${{ env.AWS_DEFAULT_REGION }}