name: 'My Custom Action'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      additional_variable_names:
        type: string
        default: ""
      additional_variable_values:
        type: string
        default: ""
    secrets:
      AWS_DEFAULT_REGION:
        description: 'Default AWS region used to build the AMI.'
    
env:
  ACTION_VAR_1: 'action_variable_1_value'
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: 'Set Environment Variables'
      if: ${{ inputs.additional_variable_names != '' }} && ${{ inputs.additional_variable_values != '' }}
      run: |
        set -f
        IFS=,
        var_name_array=(${{ inputs.additional_variable_names }})
        var_value_array=(${{ inputs.additional_variable_values }})
        for key in "${!var_name_array[@]}";
        do 
          echo "${var_name_array[$key]}=${var_value_array[$key]}" >> $GITHUB_ENV
        done
    - name: 'Print Variables'
      run: |
        echo ${{ env.ACTION_VAR_1 }}
        echo ${{ env.AWS_DEFAULT_REGION }}